### ISSUE TITLE
Cálculo SEDEX/PAC em produtos configuráveis não funciona corretamente

### ISSUE THREAD

**Issue by rjslegall** [FrenetGatewaydeFretes/frenet-magento2#11]
Olá!

Estamos enfrentando um problema para produtos configuráveis. Usamos a versão 2.2.4 do Frenet com PAC/SEDEX.
Usamos um módulo de terceiros para cálculo de frete na página do produto. 

O módulo retorna todas as modalidades de frete para produtos simples: Jadlog, SEDEX/PAC e retirar no local. 

Mas para produtos configuráveis não retorna os valores de PAC e SEDEX. Apenas no carrinho de compras vemos todas as modalidades incluindo a dos Correios.

Até o momento não temos uma solução. Alguém da Frenet pode nos ajudar?

**Comment by rjslegall** [comment]
Apenas para deixar mais claro. O módulo Frenet não é compatível com outros módulos de cálculo de frete efetuados na página do produto. Este erro prejudica quem já possui outros módulos de cálculos mais completos e já configurados nas sua lojas.

**Comment by lucas-bernardes-frenet** [comment]
Olá @rjslegall, tudo bem?

Hoje nosso módulo na última versão possui uma calculadora na página do produto, infelizmente não conseguiríamos dar suporte em módulos de terceiro como no seu caso.

Geralmente, este erro é comum quando a informação da requisição de frete está faltando alguns parâmetros, como por exemplo dimensões, etc.

Consegue por gentileza entrar em contato com suporte@frenet.com.br e nos passar o exemplo de algum link do produto, ou algo do tipo para que possamos avaliar com mais critério?

Por lá, podemos dar ao menos um encaminhamento de como prosseguir neste caso.

Espero ter ajudado.
