### ISSUE TITLE
Cotação na página do produto, não considera o Lead times do produto

### ISSUE THREAD

**Issue by jadiel-dev123** [FrenetGatewaydeFretes/frenet-magento2#12]
A um problema na funcionalidade de cotação de cep na página do produto, a cotação não leva em consideração se o produto tem Lead Times, trazendo somente o prazo normal de entrega.

**Comment by awakebrasil** [comment]
Olá, estou com o mesmo problema, conseguiu algum retorno ou solução por parte da Frenet? Obrigado.

**Comment by tiagosampaio** [comment]
Os releases `2.1.11` e `2.2.6` resolvem esse problema.
