### ISSUE TITLE
Cotação de frete calculada apenas com o método Table Rates ativo

### ISSUE THREAD

**Issue by gabrielfrtg** [FrenetGatewaydeFretes/frenet-magento2#13]
Ao utilizar o módulo Frenet no Magento 2.4.0 juntamente como o módulo One Step Checkout da Mageplaza , a cotação de frete na página de checkout é calculada apenas se o método de entrega Table Rates do Magento estiver ativa. Quando apenas o método de entrega da Frenet está ativo e os demais (como os default Flat e Table Rates) estão inativos, a cotação não é exibida. Para que a cotação seja carregada, é necessária a ativação do método Table Rates e, mesmo assim, a cotação somente é calculada após inserir o CEP juntamente com o respectivo Estado, sendo que na página do carrinho é possível calcular a cotação do frete apenas com o CEP. Ao desabilitar o módulo One Step Checkout, tudo funciona perfeitamente na página de checkout, inclusive calculando a cotação do frete apenas com o CEP, sem a necessidade de inserir o Estado.

Versões testadas:
Magento 2 nas versões 2.4.0. 2.4.1 e 2.4.2
Frenet nas versões 2.2.1, 2.2.2, 2.2.3 e 2.2.4
Mageplaza One Step Checkout nas versões 2.8.2, 2.10.2, 4.00, 4.0.1, 4.0.2, 4.0.3 e 4.0.4

**Comment by lucas-bernardes-frenet** [comment]
Olá @gabrielfrtg , tudo bem?

Hoje nossos módulos são compatíveis com as diretrizes do Magento, onde estamos de acordo com todas as exigências por eles requeridas.

Infelizmente, hoje não conseguimos garantir estabilidade com todos os módulos de terceiros como em seu caso.

Espero ter ajudado.
