### ISSUE TITLE
[cotação em cache] - A cotação em cache não é limpa quando a quote é alterada

### ISSUE THREAD

**Issue by elisei** [FrenetGatewaydeFretes/frenet-magento2#15]
A cotação do valor de frete não é limpa quando a quote sofre alterações.

## Condições
- Magento 2.4.2
- Módulo frent na versão 2.2.5

## Como replicar
- Adcione produtos ao carrinho até atingir a cotação de por exemplo de frete grátis.
- Remova produtos do carrinho até ficar abaixo do valor de frete grátis

## Resultado atual
- O cliente continua fechando com frete grátis, pois a cotação é recuperada da quote

## Resultado esperado
- O cliente receber a cotação sem o frete grátis.

**Comment by alexandercamps** [comment]
Boa tarde!
Foi liberada uma nova versão do módulo compativel com PHP 8 e Magento 2.4.
@elisei , você poderia verificar se o problema foi resolvido?
