### ISSUE TITLE
Compatibilidade com a versão 2.4.3

### ISSUE THREAD

**Issue by Samuel291** [FrenetGatewaydeFretes/frenet-magento2#16]
Olá, bom dia!

Tínhamos o módulo da Frenet instalado em nossa loja Magento na versão 2.4.3, inicialmente ele funcionava muito bem, depois começou a apresentar problemas e por fim parou de funcionar, gerava algum erro na hora de obter as cotações estourando a memória da requisição.

**Comment by tiagosampaio** [comment]
Olá @Samuel291, tudo bem?

Poderia colocar exatamente os detalhes da sua instalação?

- Versão do Magento que está utilizando.
- Versão do módulo que está dando erro.
- Se o módulo está sendo instalado via composer ou manualmente.
- Colar o log de erros e a mensagem que é gerada no momento da cotação.

Obrigado.

**Comment by Samuel291** [comment]
Olá Tiago, tive uns problemas com meu computador e só agora consegui retornar.
Respondendo ao que pediu.
Versão do Magento que está utilizando: "2.4.3"
Versão do módulo que está dando erro: "frenet/frenet-magento2": "^2.2"
Se o módulo está sendo instalado via composer ou manualmente: "composer"
Colar o log de erros e a mensagem que é gerada no momento da cotação: "Precisamos fazer uma limpeza no server e perdemos os logs da frenet =("

Mas ao tentar cotar o frete o site todo caia, porque a requisição explodia o limite de memória.

**Comment by alexandercamps** [comment]
Boa tarde!
Foi liberada uma nova versão do módulo compativel com PHP 8 e Magento 2.4.

@Samuel291 , você poderia verificar se o problema voi resolvido?
