### ISSUE TITLE
Error ao habilitar múltiplas entregas

### ISSUE THREAD

**Issue by viniciusnw** [FrenetGatewaydeFretes/frenet-magento2#20]
O erro acontece ao habilitar a funcionalidade de múltiplas entregas.

ao escolher as duas entregas o próximo passo do check-out apresenta o erro:
![image](https://user-images.githubusercontent.com/8962324/154596566-c39e8266-269f-4f0f-b320-575953a7e1e2.png)
![image](https://user-images.githubusercontent.com/8962324/154596716-1e85d58c-f4d4-44ff-8cb4-a3593c191dae.png)

com o modulo frenet-magento2 desabilitado, se tem o resultado esperado:
![image](https://user-images.githubusercontent.com/8962324/154596826-6fed71b0-ae5a-4ab9-8a1f-c8b331a3c3a5.png)

**Comment by alexandercamps** [comment]
Boa tarde!
Foi liberada uma nova versão do modulo compativel com PHP 8 e Magento 2.4.

@viniciusnw , você poderia verificar se ainda ocorre o problema nesta nova versão e me avisar aqui?
