### ISSUE TITLE
Magento 2.4.4 e PHP 8.1 Suport

### ISSUE THREAD

**Issue by redati** [FrenetGatewaydeFretes/frenet-magento2#21]
TypeError: preg_replace(): Argument #2 ($replacement) must be of type array|string, null given in /var/www/html/vendor/frenet/frenet-magento2/Model/Formatters/PostcodeNormalizer.php:30

Magento 2.4.4 e PHP 8.1

**Comment by alexandercamps** [comment]
Boa tarde!
Foi liberada uma nova versão do módulo compativel com PHP 8 e Magento 2.4.4

Qualquer duvida me avisem.

**Comment by schossler** [comment]
@alexandercamps troquei para php8.1 e obtive o erro

main.CRITICAL: TypeError: preg_replace(): Argument #2 ($replacement) must be of type array|string, null given in public_html/vendor/frenet/frenet-magento2/Model/Formatters/PostcodeNormalizer.php:30

**Comment by alexandercamps** [comment]
Oi @schossler !
Para suportar valores nulos, adicionei um tratamento no parametro replacement.
Poderia avaliar e me dar um feedback?

Obrigado,

**Comment by schossler** [comment]
funcionou valeu ...
