### ISSUE TITLE
Incompatibilidade com PHP 8.1 e Magento 2.4

### ISSUE THREAD

**Issue by profbruna** [FrenetGatewaydeFretes/frenet-magento2#26]
**Descreva o bug**

Ao solicitar o cálculo do frete no carrinho de compras, recebo o seguinte erro para a classe Frenet\Shipping\Model\Formatters\PostcodeNormalizer:
TypeError: preg_replace(): Argument #2 ($replacement) must be of type array|string, null given

Alterei a linha do preg_replace, trocando o null para '' mas não obtive sucesso e passei a receber o erro ao solicitar o cálculo do frete no carrinho de compras:

Object { code: 500, message: "Fatal Error: 'During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of TiagoSampaio\\DataObject::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /web/vendor/tiagosampaio/data-object/src/DataObject.php on line 203 in /web/vendor/magento/framework/App/ErrorHandler.…r->dispatch()\n#55 /web/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http->launch()\n#56 /web/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#57 /web/pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run()\n#58 {main}' in '/web/vendor/tiagosampaio/data-object/src/DataObject.php' on line 11", trace: "Trace is not available." }

Dessa forma não é possível prosseguir com a estimativa de entrega e consequentemente com o fechamento do pedido.

**Para Reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa que relata o que deveria ser esperado ao seguir os passos acima.

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar o problem.

**Desktop (por favor, complete as informações seguintes):**
 - Versão do Magento em que acontece o erro
 - Versão do módulo no qual o erro foi encontrado

**Smartphone (por favor, complete as informações seguintes):**

**Contexto adicional**
Adicione qualquer outro context sobre o problema aqui.

**Comment by schossler** [comment]
terá de mudar o data-object conforme o Elisei fez aqui ->
https://github.com/tiagosampaio/data-object/pull/4/commits/d064360120fa5db471ae2465acbe322278d12fba

mas vou ser sincero estou preferindo ainda o php7.4 ainda me parece mais estável ...

**Comment by profbruna** [comment]
Obrigada. Funcionou.

**Comment by alexandercamps** [comment]
Boa tarde!
Foi liberada uma nova versão compativel com PHP 8 e Magento 2.4.5 

Se tiverem problemas podem me avisar.
