### ISSUE TITLE
Erro ao instalar o frenet via composer em Magento 2.3.5-p1

### ISSUE THREAD

**Issue by pedrohenrique1986** [FrenetGatewaydeFretes/frenet-magento2#27]
Olá, esta me retornando um erro ao instalar o frenet via composer:

Erro:
  Problem 1
    - frenet/frenet-php 1.3.0 requires php ^8.0 -> your PHP version (7.3.33) does not satisfy that requirement.
    - frenet/frenet-magento2 2.4.5 requires frenet/frenet-php ^1.3.0 -> satisfiable by frenet/frenet-php[1.3.0].
    - Installation request for frenet/frenet-magento2 ^2.4 -> satisfiable by frenet/frenet-magento2[2.4.5

Versao Magento:
Magento 2.3.5-p1

Meu PHP:
PHP 7.3.33 (cli) (built: Nov  1 2022 19:28:40) ( NTS )

Comando a usar para reproduzir o erro:
composer require frenet/frenet-magento2 

Print:
![frenet](https://user-images.githubusercontent.com/13370384/199724637-1ebf7eaf-0567-4f11-a7f7-0fbd446591ac.png)

**Comment by alexandercamps** [comment]
Boa noite!
@pedrohenrique1986 , foi realizado o ajuste para suportar php 7 no plugin.
