### ISSUE TITLE
Erro ao fazer a compilação

### ISSUE THREAD

**Issue by guijn2** [FrenetGatewaydeFretes/frenet-magento2#28]
**Descreva o bug**
Quando eu faço a compilação do modulo ocorre um erro na construct (imagem em anexo)
![image](https://user-images.githubusercontent.com/112118372/200322044-f69d15fe-2712-4e69-b262-9f2486a406aa.png)

**Para Reproduzir**
Passos para reproduzir o comportamento:
bin/magento setup:di:compile 

- Testado na versão do Magento 2.4.5
- Utilizado a branch "2.4.5-develop"

**Comment by alexandercamps** [comment]
Boa tarde @guijn2 !
Você poderia me infomar com a versão do PHP instalada no servidor?

Obrigado,
