### ISSUE TITLE
Cálculo de frete na página do produto não retorna valores de frete.

### ISSUE THREAD

**Issue by rjslegall** [FrenetGatewaydeFretes/frenet-magento2#29]
Olá!

Estamos usando a versão 2.4.5.1 no Magento 2.4.5 p1
O Cálculo de frete na página do produto não retorna valores de frete.
Recebemos a seguinte mensagem:
"Desculpe. Nenhuma cotação foi encontrada para este cep."

Não há informações  de erro no frenet_request_debug.log

Alguém tb teve este problema?

**Comment by alexandercamps** [comment]
Olá @rjslegall !
Poderia enviar seu e-mail cadastrado na conta Frenet que esta com problema?

Obrigado!

**Comment by rjslegall** [comment]
Olá Alexandre!

Poderia me explicar o que precisa, não entendi? Vc é da Frenet?

Em qui., 24 de nov. de 2022 às 20:14, ALEXANDER CAMPOS <
***@***.***> escreveu:

**Comment by alexandercamps** [comment]
Sou da Frenet sim.
Confirme se vc fez a configuração, conforme o artigo abaixo?

[Configuração Magento2](https://ajuda.frenet.com.br/s/article/integracao-magento-2)

Eu preciso do e-mail que vc esta usando no seu login, com isso configo verificar a sua cotação.

Se preferir abra um chamado na Frenet, pela sua conta, que a galera de Magento 2 pode avaliar pra vc.

Obrigado.

**Comment by rjslegall** [comment]
Oi Alexandre!

obrigado pela ajuda. Antes de passar e-mail para eles, vou documentar aqui pois fica mais claro.

Instalei a versão mais recente (2.4.5.1) via composer.
Retorna frete no carrinho e checkout. Menos na página do produto.

Já usamos em outra loja Magento 2.4 a versão 2.2.4, tudo ok.

A única coisa que não fiz, conforme o link de instrução foi instalar o composer require frenet/frenet-php.
No meu cenário é necessário?

**Comment by alexandercamps** [comment]
Por padrão o frenet/frenet-php, esta como dependencia no plug-in, então não deveria ser necessário instalar.

Eu recomendo avaliar via suporte da Frenet, o que esta sendo enviaod/recebido na conta que vc está usando para os testes.

**Comment by rjslegall** [comment]
Olá! 
Alguém da Frenet poderia avaliar o problema antes de fechar a reclamação sem dizer nada...
