### ISSUE TITLE
Erro persistente ao digitar CEP incorreto

### ISSUE THREAD

**Issue by rjslegall** [FrenetGatewaydeFretes/frenet-magento2#30]
Olá
Estamos usando a versão 2.4.5.1 no Magento 2.4.5 p1

Ao digitar um CEP incorreto recebemos a seguinte mensagem:
"Something went wrong with your request. Please try again later."

Após digitar o CEP correto ainda continuamos a receber a mensagem:
"Something went wrong with your request. Please try again later."

Vemos no console os seguintes erros:

![frenet_error](https://user-images.githubusercontent.com/65203768/203996440-14e76ca5-d445-45ff-b124-6816feb235c3.jpg)

![frenet_error1](https://user-images.githubusercontent.com/65203768/203996467-6d408442-7196-4472-98bf-5304ea684b5f.png)

O Suporte da Frenet pode nos ajudar a corrigir este erro?

**Comment by alexandercamps** [comment]
Bom dia @rjslegall !
Fui informado que foi aberto um caso no suporte da Frenet e seria uma situação com as configurações da conta, não sendo necessário ajustar o módulo.

Continue a trativa diretamente com o suporte ao cliente.

Atenciosamente,

**Comment by rjslegall** [comment]
Como o suporte do Frenet está a dias sem dar uma resposta e afirma que o
problema é de configuração sendo que usamos o módulo a anos sem problema,
então estamos reabrindo este assunto.

***Temos uma instalação de teste em funcionamento caso se interessem em ver
o problema.

Estamos usando a versão 2.4.5.1 no Magento 2.4.5 p1
