### ISSUE TITLE
O Cálculo de frete na página do produto não retorna valores de frete.

### ISSUE THREAD

**Issue by rjslegall** [FrenetGatewaydeFretes/frenet-magento2#31]
Olá!

Estamos usando a versão 2.4.5.1 no Magento 2.4.5 p1
O Cálculo de frete na página do produto não retorna valores de frete.
Recebemos a seguinte mensagem:
"Desculpe. Nenhuma cotação foi encontrada para este cep."

Não há informações de erro no frenet_request_debug.log

Alguém tb teve este problema?

**Comment by schossler** [comment]
Aqui está funcionando corretamente no Magento 2.4.5-p1 e módulo frenet atualizado, abre um ticket lá no site da frenet para analisarem alguma configuração na conta.

**Comment by alexandercamps** [comment]
Bom dia @rjslegall !
Fui informado, que existe um chamado em andamento aguardando uma resposta do cliente, por ora iremos fechar o issue pois o problema não parece estar relacionado ao módulo.

Caso exista a necessidade de revisar o módulo, reabiremos o issue e liberaremos os ajustes.

Atenciosamente,

**Comment by rjslegall** [comment]
Olá!

Como o suporte do Frenet está a dias sem dar uma resposta e afirma que o
problema é de configuração sendo que usamos o módulo a anos sem problema,
então estamos reabrindo este assunto.

***Temos uma instalação de teste em funcionamento caso se interessem em ver
o problema.

Estamos usando a versão 2.4.5.1 no Magento 2.4.5 p1

**Comment by alexandercamps** [comment]
Verifiquei com o time, eles ainda não receberam algumas informações necessárias para a continuidade do atendimento.

Gentilmente, peço que verifique o e-mail enviado pelo suporte e informe as informações solicitadas.

Abs,

**Comment by rjslegall** [comment]
Olá Alexandre!

Infelizmente não houve nenhum interesse do "time" em checar, pois fazem
mais de 5 dias que enviem o Ticket e falaram que iriam analisar, mas não
fizeram nada.
Pura falta de profissionalismo. Nem para perguntar sobre informações para
entender melhor e checar... muito lamentável.

Como vc pode fechar meus bilhetes baseado em informações infundadas?
Eu sou cliente Frenet a anos e "pago" para usar, só para te informar. Então
quando precisamos de suporte é isso que recebemos.

**Comment by alexandercamps** [comment]
@rjslegall 
peço desculpas por algum transtorno que tenhamos te gerado.

Eu verifiquei no sistema de atendimento para conferir as informaçoões e anexo está uma cópia do atentidento.

Pelo que pude conferir a cronologia foi a seguinte:
- 25/11/2022 - 10:39, caso chegou ao atendimento;
- 25/11/2022 - 10:44, caso foi repassado para o time do plugin;
- 25/11/2022 - 17:22, caso foi analisado pelo time e enviado para a sua analise;
- 30/11/2022 - 08:46, caso foi respondido por você;
- 30/11/2022 - 09:12, caso foi respondido pelo time.

Não quero justificar nada, longe disso, mas pelos logs de atendimento o seu caso teve uma atuação no mesmo dia, infelizmente ao final do dia 25/11 (dia da abertura), por termos alguns outros casos e tal, e uma resposta para a solicitação do suporte chegou hoje pela manhã.

Eu peço que o atendimento continue pelo suporte, para as informações serem tratadas de uma forma mais eficiente e qualquer informação delicada (token, senha, dados pessoais) não fiquem expostas no github.

Novamente, peço desculpas caso tenhamos gerado algum aborrecimento.

![image](https://user-images.githubusercontent.com/13930823/204799708-c5a37ce8-0620-4ad5-b671-b034a056e10a.png)


Abs,

**Comment by rjslegall** [comment]
Esperarmos 5 dias para uma resposta é muito tempo porque fica claro que não
tem nenhum interesse em avaliar o caso para judar!
Tenho o email do suporte dia 25/11 quando abri o ticket. Desde então não
houve nenhuma interação até minha reclamação.

Olá, Bom Dia!
Esperamos que esteja bem! =)

Sou o Tiago, serei o responsável por lhe ajudar nesse atendimento.
Agradecemos pelo feedback!
Estamos repassando a informação para os setores responsáveis.

Atenciosamente.

Qualquer dúvida, conte conosco!

Tiago Doná

Frenet | Suporte Técnico


Em qua., 30 de nov. de 2022 às 09:47, ALEXANDER CAMPOS <
***@***.***> escreveu:
