### ISSUE TITLE
ETA stable version

### ISSUE THREAD

**Issue by schossler** [FrenetGatewaydeFretes/frenet-magento2#38]
@alexandercamps0 @tiagosampaio @alexandercamps 
Estou aguardando uma versão estável para atualizar minha loja alguma previsão para liberação ? 
Ou como instalar a versão develop sem composer ?

**Comment by alexandercamps** [comment]
Boa tarde @schossler !
Poderia me enviar por aqui, qual é a mensagem de erro que esta ocorrendo no momento da instalação da sua versão?

Informe também: Versão do PHP, Versão da instalação Magento 2 e Tipo de produto Magento 2 (Community, Enterprise ou Cloud)

Estou no aguardo das informaçoes.

Obrigado!

**Comment by schossler** [comment]
@alexandercamps 

ao rodar
composer require frenet/frenet-magento2

Higher matching version 2.4.5.4 of frenet/frenet-magento2 was found in public repository packagist.org
than 2.2.6 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,
please investigate and update package requirement to match the version from the private repository

Queria saber quando vai ter a versão 2.4.5.4 no repo do magento pois não consigo atualizar o magento e outros módulos  que estou necessitando !

**Comment by schossler** [comment]
também dá aviso

Cannot use frenet/frenet-magento2's latest version 2.2.6 as it requires php ^7.0 which is not satisfied by your platform.

pois estou usando PHP 8,1

**Comment by alexandercamps** [comment]
@schossler esta em andamento a review pela magento.com e estamos ajustando conforme os feedbacks.

Consegue me enviar os dados: Versão da instalação Magento 2 e Tipo de produto Magento 2 (Community, Enterprise ou Cloud)?

Após o aceite do magento.com, antes de liberar para prod validaremos em cada versão, são processos diferentes.

Eu gostaria de priorizar os testes na sua versão de instalação.

No aguardo.

**Comment by tiagosampaio** [comment]
@schossler, temporariamente você pode fazer o seguinte.

No seu `composer.json`, na raiz do projeto, faça a seguinte alteração.

![image](https://github.com/FrenetGatewaydeFretes/frenet-magento2/assets/1485260/86624395-e7a6-4d3f-a343-c29735a386d3)

Isso permitirá seu composer baixar o pacote na versão `2.4.5.4` diretamente do Packagist ao invés do repositório da Magento até que o mesmo esteja disponível por lá.

Abraços.

-Tiago

**Comment by schossler** [comment]
@alexandercamps 

Community 2.4.5-p1 

@tiagosampaio 

irei testar essa opção

**Comment by schossler** [comment]
@tiagosampaio 
o comando roda muito rápido sem retorno algum e gera um log (abaixo)
php bin/magento setup:di:compile

log erro
PHP Fatal error:  During inheritance of Countable: Uncaught Exception: Deprecated Functionality: Return type of Composer\Repository\FilterRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /public_html/vendor/composer/composer/src/Composer/Repository/FilterRepository.php on line 188 in /public_html/vendor/magento/framework/App/ErrorHandler.php:62

**Comment by schossler** [comment]
até corrigi esse erro acima mas aparece outro !
enfim vou testar mais ...

**Comment by schossler** [comment]
Consegui fazer update corretamente, obrigado @tiagosampaio e @alexandercamps
