### ISSUE TITLE
Calculo de frete pelo endereço de entrega

### ISSUE THREAD

**Issue by psincero** [FrenetGatewaydeFretes/frenet-magento2#4]
O módulo realiza o cálculo do frete pelo endereço de cobrança. Quando é igual o endereço de cobrança e entrega não gera problemas, mas tivemos casos do cliente utilizar o endereço de entrega diferente do de cobrança, inclusive para outro estado, e o frete ser calculado pelo de cobrança o que é errado pois mostram valores e até transportadoras inconsistentes com o destino.

Att.
Pedro Sincero

**Comment by tiagosampaio** [comment]
Olá @psincero, tudo bem?

Poderia nos descrever como reproduzir este problema? Assim conseguimos atuar diretamente na sua necessidade.

Abraços,

\- Tiago

**Comment by lucas-bernardes-frenet** [comment]
Olá @psincero,

Tentei reproduzir o problema conforme foi relatado em seu comentário e verifiquei que na hora do checkout, você consegue alterar entre os endereços de entrega e de pagamento, e quando é alterado os valores mudam conforme a origem que está cadastrada nos endereços.

Sua dificuldade era com relação a isso?

Att,
Lucas
