### ISSUE TITLE
Layout do frontend desconfigurado

### ISSUE THREAD

**Issue by schossler** [FrenetGatewaydeFretes/frenet-magento2#41]
Ontem instalei novos módulos na minha loja e atualizou o módulo da FRENET para versão 2.4.6 do módulo.
**Layout do frontend desconfigurado** 

![image](https://github.com/FrenetGatewaydeFretes/frenet-magento2/assets/1133840/7caff0db-10b7-4ffa-a7a7-4a41c54c95c5)

Comportamento antigo (versão 2.4.5 módulo).
![image](https://github.com/FrenetGatewaydeFretes/frenet-magento2/assets/1133840/1a7e7cab-b375-44f2-a380-a4b3352361a8)

Comportamento novo (versão 2.4.6 módulo).
![image](https://github.com/FrenetGatewaydeFretes/frenet-magento2/assets/1133840/998b7ed3-729d-4397-b4b9-3fd16f81db3f)

**Comment by alexandercamps** [comment]
Ola @schossler !
Eu preciso de algumas informações: 
- url de um produto da loja (podução ou teste) com a versão 2.4.5;
- url de um produto da loja (podução ou teste) com a versão 2.4.6.

Tem algum e-mail que eu possa te chamar no privado?

Fico no aguardo das informações.

Abs,

**Comment by schossler** [comment]
@alexandercamps obrigado pelo feedback, mas era uma incompatibilidade com módulo de tema já arrumei ele ! 
E está funcionando corretamente agora, obrigado e desculpe o trasntorno.
