### ISSUE TITLE
Módulo incompatível com Magento 2.4/PHP 7.4

### ISSUE THREAD

**Issue by rjslegall** [FrenetGatewaydeFretes/frenet-magento2#5]
Olá!

Estamos atualizando nossa loja para Magento 2.4.
Após efetuar o comando: composer require frenet/frenet-magento2, recebemos a seguinte mensagem:

Problem 1
    - magento/magento2-functional-testing-framework 2.6.5 requires php ~7.1.0||~7.2.0||~7.3.0 -> your PHP version (7.4.10) does not satisfy that requirement.
    - magento/magento2-functional-testing-framework 2.6.5 requires php ~7.1.0||~7.2.0||~7.3.0 -> your PHP version (7.4.10) does not satisfy that requirement.
    - magento/magento2-functional-testing-framework 2.6.5 requires php ~7.1.0||~7.2.0||~7.3.0 -> your PHP version (7.4.10) does not satisfy that requirement.
    - Installation request for magento/magento2-functional-testing-framework (locked at 2.6.5, required as ~2.6.4) -> satisfiable by magento/magento2-functional-testing-framework[2.6.5].

Temos uma incompatibilidade com o PHP atual (7.4.10) e não poderemos fazer o downgrade do PHP permanentemente. 
Poderia nos ajudar a solucionar o problema?

Obrigado desde já pela ajuda!

**Comment by tiagosampaio** [comment]
Oi, @rjslegall.

Este problema que você está tendo está sendo gerado pelo pacote chamado `magento/magento2-functional-testing-framework 2.6.5`, pois no Magento `2.4` você deveria ter a versão `^3.0` e a sua instalação está utilizando a versão `2.6.5` deste pacote, assim, quando você tenta instalar algo, o `composer` vai falhar nessa validação e bloquear a instalação para não quebrar sua plataforma.

O que você pode fazer para "forçar" a instalação? Bem, é até mais simples do que imagina, basta adicionar a opção `--ignore-platform-reqs` para fazer o composer ignorar esta validação e prosseguir com a instalação do módulo, ok? Mas cuidado, o recomendado é você atualizar as versões de suas dependências, pois ficar "burlando" as validações do composer pode ocasionar em problemas de compatibilidade em sua loja.

Abraços,

-Tiago

**Comment by rjslegall** [comment]
Olá Tiago, obrigado pela ajuda!

Qual seria o comando para "forçar"? seria este: composer require frenet/frenet-magento2 --ignore-platform-reqs?

Outra coisa, não seria melhor atualizar o magento2-functional-testing-framework  para a versão 3.0?

**Comment by tiagosampaio** [comment]
Oi, @rjslegall.

O comando é exatamente o mesmo que você está tentado executar, adicionando apenas o `--ignore-platform-reqs` no final.

```bash
composer require frenet/frenet-magento2 --ignore-platform-reqs
```
Em relação a atualizar o `magento/magento2-functional-testing-framework` minha resposta seria sim, mas é preciso verificar se existe alguma outra dependência que pode quebrar caso essa atualização seja feita. O que eu posso indicar é que você faça a alteração em um ambiente de desenvolvimento e teste para ver se quebrou alguma coisa. Se tudo der certo, é o melhor caminho.

Abraço.

\- Tiago

**Comment by yurirn** [comment]
oi @tiagosampaio tudo bem?

estou tentando instalar no magento 2.4.3 e esta retornando isso

  Problem 1
    - The requested package magento/product-community-edition (locked at 2.4.3, required as 2.4.5) is satisfiable by magento/product-community-edition[2.4.3] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Can only install one of: magento/page-builder[1.7.2, 1.7.0].
    - Can only install one of: magento/page-builder[1.7.0, 1.7.2].
    - Can only install one of: magento/page-builder[1.7.2, 1.7.0].
    - magento/product-community-edition 2.4.5 requires magento/page-builder 1.7.2 -> satisfiable by magento/page-builder[1.7.2].
    - Installation request for magento/product-community-edition 2.4.5 -> satisfiable by magento/product-community-edition[2.4.5].
    - Installation request for magento/page-builder (locked at 1.7.0) -> satisfiable by magento/page-builder[1.7.0].
    
    consegue me ajudar?

**Comment by tiagosampaio** [comment]
@yurirn tudo bem? O seu problema não é o módulo em si, mas algum conflito entre as suas versões declaradas do Magento (locked at 2.4.3, required as 2.4.5) e o módulo do PageBuilder.
