### ISSUE TITLE
Orientação sobre comportamento do módulo e da Frenet

### ISSUE THREAD

**Issue by elisei** [FrenetGatewaydeFretes/frenet-magento2#6]
Olá, 

Estou com dúvidas em relação ao comportamento do módulo.

1. Há diferença no tempo de resposta de usuários da conta gratuita para a paga?
2. Quando o cliente configura n transportadoras o fluxo de consulta interno no webservice de vocês é assíncrono ou síncrono (aguarda a resposta da primeira transportadora para então consultar a segunda...)?
3. É normal um tempo de retorno api de vocês em uma consulta inicial (sem cache) chegar a até 7 segundos em alguns horários do dia (teste realizado no plano gratuito, por hora.)?

**Comment by rafaelmancini** [comment]
Olá!
Seguem as respostas:
1. Não há diferença. O tempo de resposta poderá variar caso esteja utilizando uma integração de transportadora via API (ex: TNT, Loggi...). 
2. O processo de cotação roda em paralelo, todas as cotações são disparadas e as que responderem a tempo (parâmetro de sistema) serão retornadas para a plataforma. O suporte poderá configurar um tempo máximo de corte conforme sua necessidade, exemplo 2000 ms - desta forma de todas as opções de frete que você tenha configurado na Frenet somente serão retornadas para a loja as que responderem com menos de 2000 ms, as demais serão descartadas.
3. O parâmetro de sistema de timeout (citado anteriormente) para a plataforma Magento, é de 10s. Isso pode ser alterado. Não é comum variar tanto assim o tempo de resposta, mas como foi dito, depende muito das opções de entrega que foram configuradas. Para melhor desempenho sempre recomendamos armazenar TODAS as tabelas de frete em nossa base de dados. 
Por favor nos envie um email para suporte@frenet.com.br com os dados da sua conta para analisarmos melhor o caso.

**Comment by elisei** [comment]
@rafaelmancini 
Valeu pelo retornou vou aciona-los lá no email, valeu! :)
