### ISSUE TITLE
Dúvida referente ao módulo

### ISSUE THREAD

**Issue by ViniciusNaoDivulgue** [FrenetGatewaydeFretes/frenet-magento2#7]
Boa Tarde,
Estamos avaliando a utilização da Frenet junto a transportadora Mandaê.
O modulo foi instalando e tudo parece se comportar normalmente.
Porem ficamos com duvidas em relação a disponibilização de uma forma de acompanhamento/rastreio para o cliente.

![rastreio](https://user-images.githubusercontent.com/47072232/96163346-2b84de80-0ef0-11eb-8b95-9d574e1198b3.jpg)

Para o cliente, após ser inserido o código de acompanhamento, ficara disponível apenas o código ou ele poderá ter as informações diretamente em tela, como na imagem, ou mesmo como um link de saída pra URL direta no caso da Mandaê?
https://rastreae.com.br/resultado/{CÓDIGO RASTREIO}

Acreditamos não ser uma boa experiência de usuário, caso ele tenha que copiar o código e pesquisar por si só onde fazer tal acompanhamento.

Desde já muitíssimo obrigado.

**Comment by rafaelmancini** [comment]
Olá Vinicius, tudo bem? Não são todas as transportadoras que fornecem uma API de consulta de tracking para alimentarmos essa tela do usuário. Neste artigo descrevemos quais são elas: https://ajuda.frenet.com.br/s/article/2090931-configuracao-de-rastreio-frenet-em-lojas-magento

**Comment by nataliaalves03** [comment]
Olá @rafaelmancini! 
Seria possível obter todos os detalhes de rastreamento por meio deste endpoint?

_Tracking Info (https://frenetapi.docs.apiary.io/#reference/tracking/tracking-info/post)
Através deste serviço é possível realizar o rastreamento de um pedido e obter todas as ocorrências de entrega._
POST http://api.frenet.com.br/tracking/trackinginfo

Caso seja possível utilizar a API Frenet para rastreamento, ainda pode haver alguma transportadora sem informações detalhadas da entrega?

Obrigada!
