### ISSUE TITLE
Calculo de Frete de Produtos Configuraveis na página do produto

### ISSUE THREAD

**Issue by thuliovasc** [FrenetGatewaydeFretes/frenet-magento2#9]
Temos um problema recorrente na utilização do modulo de vocês em não conseguimos calcular o frete na pagina de produtos configuraveis. 

Se tentarmos calcular o frete na pagina de produtos simples o calculo funciona corretamente, mas no caso de produtos configuráveis ele retorna o resultado:
nullR$0,00- Este método de envio não está disponível. Para usar este método de envio, entre em contato conosco.

Em alguns temas ao selecionar a opção do produto, ele passa a retornar o resultado correto, mas em outros nem após selecionar é possivel calcular na pagina do produto, apenas após adicina-lo ao carrinho.

Vocês ja passaram por algo semelhante, existe alguma solução ou forma de passar por isso?

**Comment by rjslegall** [comment]
Olá!

Estamos enfrentando um problema parecido para produtos configuráveis. Usamos a versão 2.2.4 do Frenet.
Usamos um módulo de terceiros para cálculo de frete na página do produto. O módulo retorna todas as modalidades de frete: Jadlog e retirar no local. Mas não retorna os valores de PAC e SEDEX. Apenas no carrinho de compras vemos todas as modalidades incluindo a dos Correios.

A funcionalidade de cálculo própria do módulo Frenet para cálculo na página do produto, incluída na versão 2.2.1 funciona para produto configuráveis mas não inclui nenhuma outra modalidade que não faz parte da Frenet. Nem mesmo retirar no local.

O correto seria que qualquer retorno do Frenet ser visualizado na página de qualquer tipo de produto por qualquer módulo de cálculo de frete.

Até o momento não temos uma solução. Alguém da Frenet pode nos ajudar?

**Comment by lucas-bernardes-frenet** [comment]
Olá @thuliovasc tudo bem?

Estou tentando simular o problema e não obtive sucesso, consegue por gentileza me passar o passo a passo de como posso reproduzir o problema?

**Comment by dflamen** [comment]
Oi @bernardes93,

Estou com o mesmo problema, e isso está ligado a produtos configuráveis.

Você pode verificar acessando o link: https://www.bicimoto.com.br/bicicleta-motorizada-80cc-2-tempos-quadro-de-aco-hi-ten

Tente calcular o frete sem selecionar as cores. A mensagem retorna: Desculpe. Nenhuma cotação foi encontrada para este cep.

O correto seria alguma mensagem solicitando para selecionar a cor, ou retornar o frete correto sem selecionar a cor..

O frete apenas retorna corretamente se as cores forem selecionadas.

**Comment by tiagosampaio** [comment]
Os releases `2.1.11` e `2.2.6` resolvem esse problema.
